### PR TITLE
Fixed your issue

### PR DESCRIPTION
**Pull request by prescientmoon**
hey! im the guy who commented on your video! I fixed your issue. I commented my entire code (i recomand looking in main.ts), and you may understand how i solved it.

PS: wow, u are 9 and u are doing this?!? im 15... i started soooo late, good luck in your future projects Simon:)

PS2: i also upolaaded it to heroku: https://pi-collisions.herokuapp.com/

### CODE REVIEW

**Comment by KargJonas** [comment]
Hey, nice solution!
I use the same approach for building colliders n' stuff..

I noticed a typo in your .gitignore, which caused your _/node_modules_ to be uploaded.
And i think you accidentally copied some lines in _index.html_ 😄 

That's some pretty impressive for your age but I guess Simon tops us all... 🥇

**Comment by prescientmoon** [comment]
I copied the lines in index.html for it to work both on heroku (with a simple node server) or when db clicked:)

**Comment by prescientmoon** [comment]
And thanks for showing me the typo in .gitignore:)

**Comment by KargJonas** [comment]
No problem 😄

**Comment by prescientmoon** [comment]
How long does it takes on averege for a pull request to be accepted? I never got one accepted before (well,im rly hoping for this one)

**Comment by KargJonas** [comment]
Hmm, depends on how active the repo is.
Simon is probably busy right now :D

**Comment by KargJonas** [comment]
But if you want a pull request, maybe you could help me out with a Sierpinski triangle. (The triangles are weirdly spaced apart and I can't figure out why 😅)

**Comment by prescientmoon** [comment]
Well, when ill have some time ill try that one too (well, ill probably redo it from scratch cause im not good at understanding code that was not written by me...)

**Comment by simon-tiger** [comment]
I will add to my code later!!

**Comment by prescientmoon** [comment]
Thanks for accepting it:)

**Pull request merged**
